### ISSUE TITLE
The integration could not be loaded

### ISSUE THREAD

**Issue by p-m-x** [HASwitchPlate/openHASP-custom-component#100]
## Version of the custom_component
openHasp: 0.6.3
Homeassistant Core: 2022.6.0 and 2022.5.5

## Configuration

```yaml

---
- page: 1
  id: 2
  obj: btn
  x: 10
  y: 40
  w: 105
  h: 90
  toggle: false
  text: Normal Button
  mode: break
  align: center
- page: 1
  id: 3
  obj: btn
  x: 125
  y: 40
  w: 105
  h: 90
  toggle: true
  text: "#FFD700 Toggle# Button"
  mode: break
  align: center

```

## Describe the bug
My display (WT32-SC01) was discovered by mqtt auto discovery. 
When I try to configure component by set "full path to the jsonl file" I got error " The integration could not be loaded, try to restart Home Assistant." After restart I have openHasp component in status "Not loaded".
I tried with yaml, json and jsonl file formats, homeassistant was restarted every time. Still the same issue.

## Debug log
```
2022-06-02 23:30:01 DEBUG (MainThread) [custom_components.openhasp.config_flow] Discovered: {'node': 'plate', 'mdl': 'wt32-sc01_16MB', 'mf': 'openHASP', 'hwid': '3083987cb478', 'pages': 12, 'sw': '0.6.3', 'uri': 'http://192.168.0.66', 'input': {}, 'power': [], 'light': [], 'dim': []}

2022-06-02 23:45:36 ERROR (MainThread) [custom_components.openhasp] openHASP requires you to setup your plate objects in your YAML configuration.
2022-06-02 23:45:36 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration openhasp: Integration failed to initialize.

```text
