### ISSUE TITLE
openhasp.change_page  how to pass the page number

### ISSUE THREAD

**Issue by Sonusss** [HASwitchPlate/openHASP-custom-component#146]
I tried several ways to pass the desired page number in openhasp.yaml but couldn't get it to work.

**Comment by fvanroie** [comment]
Please share the yaml code you have tried. This should work:

```yaml
service: openhasp.change_page
target:
  entity_id: openhasp.plate01
data:
  page: 1
```

Also, test the call via Developer Tools like so:
![image](https://github.com/user-attachments/assets/23126aa0-9518-4b51-b39c-615917ad77e0)

**Comment by Sonusss** [comment]
Yes indeed it works

```
        event:
          "down":
            - service: homeassistant.toggle
              entity_id: "light.office_ceiling"
          "hold":
            - service: openhasp.change_page
              target:
                 entity_id: openhasp.plate_3
              data:
                 page: 3
```
