### ISSUE TITLE
Device not discovered

### ISSUE THREAD

**Issue by mbtronics** [HASwitchPlate/openHASP-custom-component#155]
Testing everything on latest versions:
- openHASP custom component 0.7.6
- firmware 0.7.0-rc12 from https://nightly.openhasp.com/

I'm running the firmware on a Sunton 2432S028R. On that side everything works fine, I can access the device and configure it and I'm seeing the messages in MQTT:

```
hasp/plate_radio/LWT online
hasp/plate_radio/state/page 1
hasp/plate_radio/state/idle off
hasp/plate_radio/state/antiburn {"state":"off"}
hasp/plate_radio/state/statusupdate {"node":"plate_radio","idle":"off","version":"0.7.0-rc12","uptime":7,"ssid":"Oes appartement","rssi":-56,"ip":"192.168.5.137","mac":"08:D1:F9:EE:02:24","heapFree":61256,"heapFrag":3,"core":"4.4.6","canUpdate":"false","page":1,"numPages":12,"tftDriver":"ILI9341","tftWidth":240,"tftHeight":320}
hasp/plate_radio/state/sensors {"time":"1970-01-01T00:00:07","uptimeSec":7,"uptime":"0T00:00:07","ESP32":{"Temperature":93.33}}
hasp/discovery/08d1f9ee0224 {"node":"plate_radio","mdl":"esp32-2432s028r_4MB","mf":"openHASP","hwid":"08d1f9ee0224","pages":12,"sw":"0.7.0-rc12","node_t":"hasp/plate_radio/","uri":"http://192.168.5.137","input":{},"power":[],"light":[],"dim":[]}
```
- I'm running an up-to-date version of Home Assistant with HACS. I tried reinstalling both the firmware on the device and the openHASP component multiple times.

![Image](https://github.com/user-attachments/assets/c54ff415-d593-4c9f-9deb-6104a1677cb9)

- There are no errors in the log, the only mention of openHASP is this:
```
2025-02-11 06:44:30.018 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration openhasp which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
```

- MQTT discovery is enabled, and MQTT is working for several other devices.

![Image](https://github.com/user-attachments/assets/2811cf2d-22dd-4222-8c56-3239a81d8de7)

- I added this to configuration.yaml:
```
openhasp:
  plate_radio:
    objects:
      - obj: "p0b1"  # temperature label on all pages
        properties:
          "text": '{{ states("sensor.my_room_temperature") }}°C'
      - obj: "p1b2"  # light-switch toggle button
        properties:
          "val": '{{ 1 if states("light.my_room") == "on" else 0 }}'
          "text": '{{ "\uE6E8" if is_state("light.my_room", "on") else "\uE335" | e }}'
        event:
          "up":
            - service: homeassistant.toggle
              entity_id: "light.my_room"
      - obj: "p1b3"  # dropdown
        event:
          "changed":
            - service: persistent_notification.create
              data:
                message: I like {{ text }}
```
- tried rebooting home assistant and the device multiple times

I'm getting no notifications about new devices, no new entities or devices. I can debug this and can try custom code if needed, but for the moment I don't have an idea where to start.
Any help or suggestions would be greatly appreciated, I would really like to try this project.

**Comment by wjnelson78** [comment]
**Hello!** Since you’ve tried multiple re-installs and the device is definitely sending valid MQTT messages, I’m curious about a few setup details:

1. **Did you add the openHASP integration itself in Home Assistant’s “Integrations” screen?**

• Even when installed via HACS, some custom components also need to be manually added in **Settings → Devices & Services → Add Integration**. Confirm it’s actually loaded and doesn’t show as “Not loaded” in your list of integrations.

2. **Have you verified MQTT discovery is fully enabled?**

• Check **Settings → Devices & Services → MQTT → Configure** and ensure “Enable discovery” is on. Although you wrote that MQTT discovery is enabled, it’s good to verify the discovery prefix matches your device’s topics if you customized them.

3. **Is your configuration.yaml referencing the openHASP domain correctly?**

• You mentioned:

```
openhasp:
  plate_radio:
    objects:
      ...
```

Make sure that’s aligned with how the openHASP integration expects YAML. If it doesn’t match or the slug is off, Home Assistant can silently ignore it.

  

4. **Does the Home Assistant log show any mention of openHASP ignoring the config or being unable to find the plate?**

• Check for lines like No YAML configuration found for 'plate_radio' or Could not find domain openhasp. If you see nothing, it suggests the integration may not be fully initializing.

5. **Do you see the device or entity in Developer Tools → States or the Entities tab under “filter by integration”?**

• Sometimes the new device doesn’t show in the main Devices & Services page if the integration itself never finished setup. It might show in Developer Tools if partial discovery succeeded.

  

If you can confirm all these are set, we can dig deeper into logs or see if the custom component is loading properly. Let me know what you find!
