### ISSUE TITLE
Feature request: wrapper service for any command

### ISSUE THREAD

**Issue by nagyrobi** [HASwitchPlate/openHASP-custom-component#50]
**Is your feature request related to a problem? Please describe.**
openHASP supports a handful of [commands](https://haswitchplate.github.io/openHASP-docs/0.6/commands/). Some of them would be useful in HA automations, like setting [dim values](https://haswitchplate.github.io/openHASP-docs/0.6/integrations/home-assistant/sampl_autom/#turn-on-moodlight-when-backlight-off-and-vice-versa) or [change theme](https://github.com/HASwitchPlate/openHASP/discussions/167) based on day/night, etc. 

Instead of having services in HA translated to each command, we could use one single service which could wrap them all in one.

**Describe the solution you'd like**
A universal service which would accept 2 or 3 parameters:
- command topic (if the firmware accepts commands on other topics also, like config)
- keyword
- parameter(s)

```
    - service:  openhasp.command
      target:
        entity_id: openhasp.plate35
      data:
        command: 'config'
        keyword: 'gui'
        parameters: '{"idle2":0}'
```
If the `config` or any other commands except `command` would be deprecated, only the `keyword` and `parameters` would suffice.

**Describe alternatives you've considered**
Sending commands directly to the plate is currently possible outside the component like this example:
```
    - service: mqtt.publish
      data:
        topic: hasp/plate35/config/gui
        payload: '{"idle2":0}'
```
Instead of this, it would be a lot better to wrap this inside the component like above, as they can be used with automations and blueprints more consistently. You can reference to a plate universally using it's entity_id, instead of having to keep separately track of MQTT topics belonging to that plate.

**Additional context**
Extra benefit is that commands list can freely change on the firmware side, the component doesn't have to implement new services for them if they are requested, changed or added.

**Comment by nagyrobi** [comment]
Some examples:

Jump to page:
```
service: openhasp.command
data:
  keyword: page
  parameters: '1'
target:
  entity_id: openhasp.plate_3
```

Next page:
```
service: openhasp.command
data:
  keyword: page
  parameters: 'next'
target:
  entity_id: openhasp.plate_3
```

Set Long idle time:
```
service: openhasp.command
data:
  keyword: '{"idle2":120}'
  command: config/gui
target:
  entity_id: openhasp.plate_3
```

Draw BSOD:
```
service: openhasp.command
data:
  keyword: jsonl
  parameters: >-
    {"page":0,"id":99,"obj":"obj","x":0,"y":0,"w":240,"h":320,"radius":0,"hidden":0,"bg_grad_dir":0,"bg_color":"blue"}
target:
  entity_id: openhasp.plate_3
```

Delete BSOD:
```
service: openhasp.command
data:
  keyword: p0b99.delete
target:
  entity_id: openhasp.plate_3
```

**Comment by dgomes** [comment]
**keyword** is very misleading, specially in the "Set long idle time" example

**Comment by fvanroie** [comment]
I'm thinking along the lines of raw mqtt messages like:
```yaml
service: openhasp.publish
data:
  topic: command/jsonl
  payload: >-
    {"page":0,"id":99,"obj":"obj","x":0,"y":0,"w":240,"h":320,"radius":0,"hidden":0,"bg_grad_dir":0,"bg_color":"blue"}
target:
  entity_id: openhasp.plate_3
```
to send anything without validation.

Other more specific services can handle specific commands with input validation as required.
