### ISSUE TITLE
Feature request: allow condition in events

### ISSUE THREAD

**Issue by nagyrobi** [HASwitchPlate/openHASP-custom-component#65]
**Is your feature request related to a problem? Please describe.**
I'd like to display a message on the plate when a button is pressed, but only when the sun is up.

**Describe the solution you'd like**
Use conditions, pretty much like in automations, in object events.

```
      - obj: "p2b2"  # light-switch toggle button warning
        event:
          "down":
            - condition: template
              value_template: "{{ (states('switch.plate_4_switch_12') == 'on' and state_attr('sun.sun','elevation') > 15) }}"
            - service: openhasp.command
              target:
                entity_id: openhasp.plate_4
              data:
                keyword: jsonl
                parameters: >-
                  {"page":2,"id":200,"obj":"obj","x":5,"y":55,"w":230,"h":160,"shadow_opa":140,"shadow_color":"black","shadow_width":20,"shadow_spread":0}
                  {"page":2,"id":201,"obj":"label","parentid":200,"x":10,"y":10,"w":215,"h":110,"text_font":24,"align":"center","text":"\uE595 It's daytime!\nPlease pull up\nthe covers instead!"}
                  {"page":2,"id":202,"obj":"btn","parentid":200,"x":20,"y":110,"w":190,"h":40,"text":"Thank you: a greener world","mode":"break","align":"center"}
```

**Describe alternatives you've considered**
Putting this in a script outside the component. But this makes the whole thing very clunky if you have lots of things like this.

**Additional context**
