### ISSUE TITLE
push_image service not working

### ISSUE THREAD

**Issue by megawubs** [HASwitchPlate/openHASP-custom-component#73]
## Configuration

```yaml

service: openhasp.push_image
target:
  entity_id: openhasp.plate
data:
  image: https://megawubs.duckdns.org/local/images/image.png
  obj: p2b17

```

```json
{"page":1,"id":17,"obj":"img","x":230, "y":30, "w":70,"h":70, "border_color":"white", "border_opa":0, "src":"/littlefs/genietmomentjes.png", "auto_size":0}
```

## Describe the bug
I'm unable to push an image to an image obj on my m5stack core 2. It doesn't matter if I add a url or path from /littlefs/*.png. The initial image is shown, but i'm unable to update it. 

## Debug log

```text

[139951158890064] Error handling message: invalid url for dictionary value @ data['image']. Got None

```
