### ISSUE TITLE
Question/Feature: Plate MQTT Name from inside template inside Event Handler?

### ISSUE THREAD

**Issue by erwin** [HASwitchPlate/openHASP-custom-component#92]
Assuming we start with the "[Simple Page Navigation](https://openhasp.haswitchplate.com/0.6.3/integrations/examples/example-pagination/#services)" openHASP example...

Perhaps this is already possible, but I haven't figured out a way to make it work.

Let's say I have:

```yaml
# configuration.yaml
openhasp:
  plate_foo:
    objects: !include openhasp.yaml
  plate_bar:
    objects: !include openhasp.yaml
  plate_baz:
    objects: !include openhasp.yaml
```

```yaml
# openhasp.yaml
     - obj: "p0b2"            
       event:            
         "down":             
           - service: persistent_notification.create
             data:                         
                message: Some way to get plate name? Maybe inside {{ state.state }}                
```

My goal is to handle the "home" (back) action via home-assistant, rather than via the built in openhasp `action:back` function.

![image](https://user-images.githubusercontent.com/11534217/156965027-37384d3c-dca2-41ed-9f3c-1dd5a5f7b3a8.png)

This way I can have plates in different rooms that start on their own "default" page, but keep all of the configuration global.

When pressing "home" on the master bedroom plate, home would be page 1 (the default).
But when pressing "home" on the entry plate, home would actually be page 4
And "home" on the living room plate would be page 3.

It's straight forward to send the "go to page" function but no idea how I can get the current plate name.

```yaml
  - obj: "p0b2"                                                                    
    event:                             
      "down":               
        - service: mqtt.publish
          data:
            topic: hasp/{{ HOW DO I GET THE PLATE NAME }}/command/page
            payload: '5'
```

Since the openhasp-custom-component is just responding to an MQTT request, the custom component must know which plate is involved to dispatch to the correct event handler, but I haven't figured out how to pull that into a template to respond with an MQTT message back to that same plate.
